#!/bin/bash
sync
cd "$(dirname $0)"

CONF=drehbank.ini
echo > $CONF
for i in seq 0 30; do
	echo "## DO NOT CHANGE - AUTOGENERATED from config_parts/* ##" >> $CONF;
done
for file in config_parts/*.ini; do
	cat config_parts/separator >> $CONF
	echo "####### $file #####" >> $CONF
	cat $file >> $CONF
done
linuxcnc drehbank.ini
mv drehbank.ini drehbank.ini.old
